# Generated by Django 5.2.13 on 2026-07-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Em andamento'), ('C', 'Concluída')], default='P', max_length=1)),
                ('prazo', models.DateTimeField()),
            ],
        ),
    ]
